name: CI

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml

  test:
    name: Test
    needs: check
    uses: ./.github/workflows/test.yml

  doc:
    name: Docgen
    needs: check
    uses: ./.github/workflows/docgen.yml

  release:
    name: Release
    needs: 
      - test
      - doc
    uses: ./.github/workflows/release.yml
    secrets: inherit
